#! /bin/sh

### Start helper services ###
~/.local/scripts/launch_polybar.sh
pgrep -x sxhkd > /dev/null || sxhkd &
picom --config ~/.config/picom/picom.conf &
feh --bg-fill ~/.local/share/graewolf/backgrounds/Clearnight.jpg &
udiskie &
lxsession &
xsetroot -cursor_name left_ptr
xset m 0 0
sleep 2 && xsettingsd &

### Basic Rules ###
bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         0
bspc config window_gap          5
bspc config top_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config focus_follows_pointer true
#bspc config pointer_follows_focus true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

### Resize and move windows with mouse ###
bspc config pointer_modifier mod4
bspc config pointer_action1 none
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus any

### Decorations ###
bspc config border_width 2
bspc config focused_border_color "#cba6f7"
bspc config normal_border_color "#6c7086"

#bspc rule -a Firefox desktop='^6' follow=off focus=off
#bspc rule -a Steam desktop='^3'
#bspc rule -a Lutris desktop='^3'
#bspc rule -a obs desktop='^7'
#bspc rule -a discord desktop='^9'
#bspc rule -a evolution desktop='^2' focus=on
#bspc rule -a spotify desktop='^10'
#bspc rule -a vlc state=floating
#bspc rule -a Surf state=tiled

### Inactivity handling ###
#xset s blank
#xset dpms 0 0 300

### Start idle wather ###
#~/.local/scripts/idle-wathcer &
