/* colors.h — GENERATED by voidwolf-theme; do not hand-edit */
static const char col_gray1[]       = "#0b0c0e"; /* bg / bar bg */
static const char col_gray2[]       = "#2a2e35"; /* border unfocused */
static const char col_gray3[]       = "#e6e8eb"; /* fg */
static const char col_gray4[]       = "#0b0c0e"; /* sel fg */
static const char col_cyan[]        = "#e6a23c"; /* accent / sel */
static const char col_urgborder[]   = "#f07178";

static const char *colors[][3] = {
	/*               fg         bg         border   */
	[SchemeNorm] = { col_gray3, col_gray1, col_gray2 },
	[SchemeSel]  = { col_gray4, col_cyan,  col_cyan  },
};
