/* colors.h — GENERATED by voidwolf-theme; do not hand-edit */
static const char col_gray1[]       = "#0c0d10"; /* bg / bar bg */
static const char col_gray2[]       = "#3c3d3f"; /* border unfocused */
static const char col_gray3[]       = "#9a5525"; /* fg */
static const char col_gray4[]       = "#9a5525"; /* sel fg */
static const char col_cyan[]        = "#35241f"; /* accent / sel */
static const char col_urgborder[]   = "#111116";

static const char *colors[][3] = {
	/*               fg         bg         border   */
	[SchemeNorm] = { col_gray3, col_gray1, col_gray2 },
	[SchemeSel]  = { col_gray4, col_cyan,  col_cyan  },
};
